In [ ]:
import numpy as np 
import pandas as pd
import seaborn as sns 
import  matplotlib.pyplot as plt

In [4]:
testing_data= pd.read_csv("Testing.csv")
training_data = pd.read_csv("Training.csv")

In [10]:
training_data.head()
training_data.drop("Unnamed: 133",axis = 1)

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,(vertigo) Paroymsal Positional Vertigo
4916,0,1,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,Acne
4917,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Urinary tract infection
4918,0,1,0,0,0,0,1,0,0,0,...,0,0,1,1,1,1,0,0,0,Psoriasis
4919,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,Impetigo

In [12]:
training_data.info
testing_data.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergy
2,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,GERD
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Chronic cholestasis
4,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Drug Reaction

In [17]:
training_data= pd.DataFrame(training_data)
testing_data = pd.DataFrame(testing_data)
data = pd.concat([training_data,testing_data])

In [31]:
new_data= data.drop("Unnamed: 133",axis =1)
new_data.shape
print(list(new_data.columns))

['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing', 'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity', 'ulcers_on_tongue', 'muscle_wasting', 'vomiting', 'burning_micturition', 'spotting_ urination', 'fatigue', 'weight_gain', 'anxiety', 'cold_hands_and_feets', 'mood_swings', 'weight_loss', 'restlessness', 'lethargy', 'patches_in_throat', 'irregular_sugar_level', 'cough', 'high_fever', 'sunken_eyes', 'breathlessness', 'sweating', 'dehydration', 'indigestion', 'headache', 'yellowish_skin', 'dark_urine', 'nausea', 'loss_of_appetite', 'pain_behind_the_eyes', 'back_pain', 'constipation', 'abdominal_pain', 'diarrhoea', 'mild_fever', 'yellow_urine', 'yellowing_of_eyes', 'acute_liver_failure', 'fluid_overload', 'swelling_of_stomach', 'swelled_lymph_nodes', 'malaise', 'blurred_and_distorted_vision', 'phlegm', 'throat_irritation', 'redness_of_eyes', 'sinus_pressure', 'runny_nose', 'congestion', 'chest_pain', 'weakness_in_limbs', 'fast_heart_rate', 'pain_during_bowel_movements', 'pain_in_anal_region', 'bloody_stool', 'irritation_in_anus', 'neck_pain', 'dizziness', 'cramps', 'bruising', 'obesity', 'swollen_legs', 'swollen_blood_vessels', 'puffy_face_and_eyes', 'enlarged_thyroid', 'brittle_nails', 'swollen_extremeties', 'excessive_hunger', 'extra_marital_contacts', 'drying_and_tingling_lips', 'slurred_speech', 'knee_pain', 'hip_joint_pain', 'muscle_weakness', 'stiff_neck', 'swelling_joints', 'movement_stiffness', 'spinning_movements', 'loss_of_balance', 'unsteadiness', 'weakness_of_one_body_side', 'loss_of_smell', 'bladder_discomfort', 'foul_smell_of urine', 'continuous_feel_of_urine', 'passage_of_gases', 'internal_itching', 'toxic_look_(typhos)', 'depression', 'irritability', 'muscle_pain', 'altered_sensorium', 'red_spots_over_body', 'belly_pain', 'abnormal_menstruation', 'dischromic _patches', 'watering_from_eyes', 'increased_appetite', 'polyuria', 'family_history', 'mucoid_sputum', 'rusty_sputum', 'lack_of_concentration', 'visual_disturbances', 'receiving_blood_transfusion', 'receiving_unsterile_injections', 'coma', 'stomach_bleeding', 'distention_of_abdomen', 'history_of_alcohol_consumption', 'fluid_overload.1', 'blood_in_sputum', 'prominent_veins_on_calf', 'palpitations', 'painful_walking', 'pus_filled_pimples', 'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting', 'small_dents_in_nails', 'inflammatory_nails', 'blister', 'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis']

In [43]:
features = ["chest_pain","breathlessness","sweating" , "fast_heart_rate","fatigue" , "dizziness" ,"increased_appetite","obesity" ,"irritability" , "polyuria" ,"watering_from_eyes" , "chills",
           "continuous_sneezing","joint_pain","stomach_pain","muscle_wasting","weight_gain","weight_loss","lethargy","irregular_sugar_level",
           "high_fever","dehydration","nausea","malaise","blurred_and_distorted_vision","runny_nose","muscle_weakness","unsteadiness","bladder_discomfort",
           "muscle_pain","family_history","prognosis","vomiting","anxiety","restlessness","cough","sunken_eyes","sweating",
           "diarrhoea","loss_of_appetite","throat_irritation","redness_of_eyes","congestion","weakness_in_limbs","visual_disturbances"]

In [46]:
updated_data =new_data[features]

In [47]:
updated_data

,chest_pain,breathlessness,sweating,fast_heart_rate,fatigue,dizziness,increased_appetite,obesity,irritability,polyuria,...,cough,sunken_eyes,sweating,diarrhoea,loss_of_appetite,throat_irritation,redness_of_eyes,congestion,weakness_in_limbs,visual_disturbances
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [48]:
updated_data.isnull().sum()

chest_pain                      0
breathlessness                  0
sweating                        0
fast_heart_rate                 0
fatigue                         0
dizziness                       0
increased_appetite              0
obesity                         0
irritability                    0
polyuria                        0
watering_from_eyes              0
chills                          0
continuous_sneezing             0
joint_pain                      0
stomach_pain                    0
muscle_wasting                  0
weight_gain                     0
weight_loss                     0
lethargy                        0
irregular_sugar_level           0
high_fever                      0
dehydration                     0
nausea                          0
malaise                         0
blurred_and_distorted_vision    0
runny_nose                      0
muscle_weakness                 0
unsteadiness                    0
bladder_discomfort              0
muscle_pain                     0
family_history                  0
prognosis                       0
vomiting                        0
anxiety                         0
restlessness                    0
cough                           0
sunken_eyes                     0
sweating                        0
diarrhoea                       0
loss_of_appetite                0
throat_irritation               0
redness_of_eyes                 0
congestion                      0
weakness_in_limbs               0
visual_disturbances             0
dtype: int64

In [49]:
X = updated_data.drop("prognosis",axis =1 )
Y = updated_data["prognosis"]

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
X_train , X_test , y_train , y_test = train_test_split(
    X , Y , test_size = 0.28,random_state = 512)

In [54]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, criterion='gini', max_depth=None, min_samples_split=2,
                               min_samples_leaf=1,
                               min_weight_fraction_leaf=0.0, max_features='sqrt', max_leaf_nodes=None, min_impurity_decrease=0.0,
                               bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, 
                               warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None, monotonic_cst=None)

In [55]:
model.fit(X_train , y_train)

RandomForestClassifier()

In [56]:
y_pred = model.predict(X_test)

In [57]:
y_pred

array(['Heart attack', 'Peptic ulcer diseae', 'GERD', ..., 'hepatitis A',
       'Chicken pox', 'Hepatitis D'], shape=(1390,), dtype=object)

In [58]:
print(list(y_pred))

['Heart attack', 'Peptic ulcer diseae', 'GERD', 'Acne', 'AIDS', 'Alcoholic hepatitis', 'Tuberculosis', 'Hepatitis D', 'hepatitis A', 'Migraine', 'Hypoglycemia', 'Peptic ulcer diseae', 'Tuberculosis', 'Alcoholic hepatitis', 'Bronchial Asthma', 'Allergy', 'hepatitis A', 'Pneumonia', 'Acne', 'Gastroenteritis', '(vertigo) Paroymsal  Positional Vertigo', 'Acne', 'Dengue', 'AIDS', 'Chicken pox', 'Hyperthyroidism', 'Typhoid', 'Hypoglycemia', 'Acne', 'Peptic ulcer diseae', 'Alcoholic hepatitis', 'Varicose veins', '(vertigo) Paroymsal  Positional Vertigo', 'Tuberculosis', 'Pneumonia', 'Arthritis', 'Common Cold', 'hepatitis A', 'Diabetes ', 'Alcoholic hepatitis', 'Peptic ulcer diseae', 'Migraine', 'Common Cold', '(vertigo) Paroymsal  Positional Vertigo', 'Osteoarthristis', 'AIDS', 'hepatitis A', 'Chicken pox', 'hepatitis A', 'Varicose veins', 'Allergy', 'Alcoholic hepatitis', 'Osteoarthristis', 'Acne', 'Hypertension ', 'Acne', 'Hepatitis E', 'Hypothyroidism', 'Impetigo', 'Common Cold', 'Drug Reaction', 'Cervical spondylosis', 'Tuberculosis', 'Arthritis', 'Hyperthyroidism', 'Tuberculosis', 'Hyperthyroidism', 'Migraine', 'hepatitis A', 'Alcoholic hepatitis', 'Urinary tract infection', 'GERD', '(vertigo) Paroymsal  Positional Vertigo', 'Migraine', 'Hypothyroidism', 'Alcoholic hepatitis', 'Bronchial Asthma', 'Acne', 'Urinary tract infection', 'Hepatitis D', 'Acne', 'Acne', 'Typhoid', 'Common Cold', 'Hepatitis D', 'AIDS', 'Bronchial Asthma', 'Urinary tract infection', 'Hypothyroidism', 'Urinary tract infection', 'Hepatitis D', 'Chicken pox', 'Acne', 'Drug Reaction', 'GERD', 'Hepatitis C', 'Common Cold', 'Acne', 'Malaria', 'Migraine', 'hepatitis A', 'Hepatitis E', 'Chronic cholestasis', 'Malaria', 'Hyperthyroidism', 'Cervical spondylosis', 'Alcoholic hepatitis', 'Common Cold', 'Drug Reaction', 'Osteoarthristis', 'Hypoglycemia', 'Hepatitis D', 'Gastroenteritis', 'Cervical spondylosis', 'GERD', 'Diabetes ', 'Alcoholic hepatitis', 'Tuberculosis', 'Hypoglycemia', 'Acne', 'Pneumonia', 'Hyperthyroidism', 'Hepatitis B', 'Osteoarthristis', 'Bronchial Asthma', 'Varicose veins', 'hepatitis A', 'Drug Reaction', 'Urinary tract infection', 'Typhoid', 'Hepatitis D', 'Hypoglycemia', 'Tuberculosis', 'Hypothyroidism', 'Typhoid', 'Migraine', 'Allergy', 'Hypothyroidism', '(vertigo) Paroymsal  Positional Vertigo', 'Hypoglycemia', 'Alcoholic hepatitis', 'Dengue', 'Chronic cholestasis', 'Jaundice', 'AIDS', 'Osteoarthristis', 'Acne', 'GERD', 'Malaria', 'Allergy', 'GERD', 'hepatitis A', 'Hepatitis C', 'Osteoarthristis', 'Pneumonia', '(vertigo) Paroymsal  Positional Vertigo', 'GERD', 'Hypoglycemia', 'Urinary tract infection', 'Malaria', 'Acne', 'Dengue', 'Cervical spondylosis', 'Alcoholic hepatitis', 'Hyperthyroidism', 'Hepatitis B', 'Common Cold', 'Hepatitis D', 'Acne', 'Impetigo', 'Chronic cholestasis', 'Migraine', 'Heart attack', 'Arthritis', 'Chicken pox', 'Bronchial Asthma', 'Migraine', 'Hyperthyroidism', 'Tuberculosis', 'Tuberculosis', 'Impetigo', 'Hypertension ', 'Hepatitis C', 'Migraine', 'Pneumonia', 'Drug Reaction', 'Hepatitis B', 'Peptic ulcer diseae', 'Alcoholic hepatitis', 'Hypothyroidism', 'Acne', 'AIDS', 'Hypoglycemia', 'Osteoarthristis', 'Hypertension ', 'Heart attack', 'Diabetes ', 'hepatitis A', 'Arthritis', 'Osteoarthristis', 'hepatitis A', 'Acne', 'GERD', 'Acne', 'Urinary tract infection', 'Alcoholic hepatitis', 'Acne', 'Acne', 'Hepatitis C', 'Common Cold', 'Alcoholic hepatitis', 'Chicken pox', 'Common Cold', 'Osteoarthristis', 'Malaria', 'Tuberculosis', 'Migraine', 'Hepatitis B', 'Alcoholic hepatitis', 'Diabetes ', 'Migraine', 'Migraine', 'Hepatitis D', 'Chronic cholestasis', 'Bronchial Asthma', 'Cervical spondylosis', '(vertigo) Paroymsal  Positional Vertigo', 'Dengue', 'Peptic ulcer diseae', 'AIDS', 'Drug Reaction', 'Alcoholic hepatitis', 'Chicken pox', 'Urinary tract infection', 'Common Cold', 'Hepatitis D', 'Hypothyroidism', 'Acne', 'Gastroenteritis', 'Dengue', 'Malaria', 'Diabetes ', 'Arthritis', 'Hypertension ', 'Acne', 'Chicken pox', 'AIDS', 'Migraine', 'Dengue', 'Varicose veins', 'Hepatitis E', 'Urinary tract infection', 'Hypothyroidism', 'Gastroenteritis', 'Drug Reaction', 'Typhoid', 'Pneumonia', 'Acne', '(vertigo) Paroymsal  Positional Vertigo', 'Heart attack', 'Typhoid', 'Hypothyroidism', 'Acne', 'Impetigo', 'Dengue', 'Bronchial Asthma', 'Common Cold', 'Diabetes ', 'Impetigo', 'Osteoarthristis', 'Peptic ulcer diseae', 'Chronic cholestasis', 'Hepatitis B', 'Drug Reaction', 'Tuberculosis', 'hepatitis A', 'Osteoarthristis', 'Common Cold', '(vertigo) Paroymsal  Positional Vertigo', 'Hepatitis B', 'Varicose veins', 'Dengue', 'Hypertension ', 'Hepatitis C', 'Heart attack', 'Alcoholic hepatitis', 'Dengue', 'Typhoid', 'Acne', 'Osteoarthristis', 'Drug Reaction', 'Hypoglycemia', 'Heart attack', 'Hepatitis B', 'Drug Reaction', 'Dengue', 'Hepatitis C', 'Varicose veins', 'Pneumonia', 'Peptic ulcer diseae', 'Acne', 'Pneumonia', 'Typhoid', 'Peptic ulcer diseae', 'hepatitis A', 'Pneumonia', 'Bronchial Asthma', 'Bronchial Asthma', 'Arthritis', 'Hepatitis C', 'Hypertension ', 'Gastroenteritis', 'Drug Reaction', 'Chronic cholestasis', 'Chronic cholestasis', 'Hypoglycemia', 'Bronchial Asthma', 'Malaria', 'Arthritis', 'Hypertension ', 'Hypothyroidism', 'Hypertension ', 'GERD', 'Bronchial Asthma', 'Dengue', 'Osteoarthristis', 'Bronchial Asthma', 'Malaria', 'Osteoarthristis', 'Hypothyroidism', 'hepatitis A', 'Hepatitis D', 'Impetigo', 'AIDS', 'Cervical spondylosis', 'Peptic ulcer diseae', 'Common Cold', 'Heart attack', 'Tuberculosis', 'AIDS', 'Acne', 'Hypertension ', 'Dengue', 'AIDS', 'Hepatitis B', 'Peptic ulcer diseae', 'Hypertension ', 'Alcoholic hepatitis', 'GERD', 'AIDS', 'Chronic cholestasis', 'Acne', 'Gastroenteritis', 'Cervical spondylosis', 'Diabetes ', 'Malaria', 'Acne', 'Drug Reaction', 'GERD', 'Hyperthyroidism', 'Drug Reaction', '(vertigo) Paroymsal  Positional Vertigo', 'Acne', 'Jaundice', 'Hepatitis D', 'Acne', 'Arthritis', 'Alcoholic hepatitis', 'Bronchial Asthma', 'Urinary tract infection', 'Arthritis', 'Acne', 'Peptic ulcer diseae', 'Alcoholic hepatitis', 'Acne', '(vertigo) Paroymsal  Positional Vertigo', 'Osteoarthristis', 'Common Cold', 'Malaria', 'GERD', 'Cervical spondylosis', 'Typhoid', 'Migraine', 'Urinary tract infection', 'Hyperthyroidism', 'Acne', 'Varicose veins', 'Pneumonia', 'Common Cold', 'Migraine', 'Hepatitis C', 'AIDS', 'Allergy', 'AIDS', 'Chicken pox', 'Jaundice', 'Acne', 'Alcoholic hepatitis', 'Osteoarthristis', 'Peptic ulcer diseae', 'Osteoarthristis', 'Impetigo', 'Hypoglycemia', 'Hepatitis D', 'Bronchial Asthma', 'Hepatitis D', 'Hepatitis D', 'Typhoid', 'Hepatitis E', 'Gastroenteritis', 'Heart attack', 'Allergy', 'Hepatitis E', 'Tuberculosis', 'Osteoarthristis', 'Pneumonia', 'Osteoarthristis', 'Acne', 'GERD', 'Acne', 'Acne', 'Urinary tract infection', 'Hyperthyroidism', 'Hepatitis C', 'Hepatitis B', 'Acne', 'Hypothyroidism', 'Malaria', 'Alcoholic hepatitis', 'Chronic cholestasis', 'Drug Reaction', 'Tuberculosis', 'Acne', 'Migraine', 'Alcoholic hepatitis', 'Alcoholic hepatitis', 'Heart attack', 'Hyperthyroidism', '(vertigo) Paroymsal  Positional Vertigo', 'Hepatitis E', 'Hypothyroidism', 'Drug Reaction', 'Acne', 'Chronic cholestasis', 'Migraine', 'Hypertension ', 'Bronchial Asthma', 'Pneumonia', 'Bronchial Asthma', 'Varicose veins', 'Acne', 'Cervical spondylosis', 'Bronchial Asthma', 'Alcoholic hepatitis', 'Chronic cholestasis', 'Diabetes ', 'Bronchial Asthma', 'Hyperthyroidism', 'Chicken pox', 'Jaundice', 'Typhoid', 'Hypoglycemia', 'Acne', 'Bronchial Asthma', 'Dengue', 'Heart attack', 'Varicose veins', 'Alcoholic hepatitis', 'Jaundice', 'Alcoholic hepatitis', 'Hepatitis B', 'Hepatitis B', 'Gastroenteritis', 'Osteoarthristis', 'Hepatitis E', 'Hepatitis E', 'Acne', 'Common Cold', 'Varicose veins', 'Common Cold', 'Bronchial Asthma', 'Urinary tract infection', 'Osteoarthristis', 'Malaria', 'Acne', 'Heart attack', 'Jaundice', 'GERD', 'Hypothyroidism', 'Typhoid', 'Allergy', 'Chronic cholestasis', 'Gastroenteritis', 'Pneumonia', 'Gastroenteritis', 'Acne', 'Hepatitis D', 'Hypertension ', 'Heart attack', 'Acne', 'Chronic cholestasis', 'Arthritis', 'Alcoholic hepatitis', 'Diabetes ', '(vertigo) Paroymsal  Positional Vertigo', 'Varicose veins', 'Allergy', 'GERD', 'Hepatitis C', 'Jaundice', 'Common Cold', 'Jaundice', 'Bronchial Asthma', 'Typhoid', 'Osteoarthristis', 'Hypothyroidism', 'Hepatitis B', 'Heart attack', 'Chronic cholestasis', 'Alcoholic hepatitis', 'Osteoarthristis', 'Hypoglycemia', 'Hypertension ', 'Jaundice', 'Malaria', 'Acne', 'Typhoid', 'Alcoholic hepatitis', 'Gastroenteritis', 'GERD', 'Acne', 'Drug Reaction', 'Peptic ulcer diseae', 'Hepatitis C', 'Varicose veins', 'Acne', 'Hypoglycemia', 'Diabetes ', 'Arthritis', 'Gastroenteritis', 'Allergy', 'Allergy', 'Common Cold', 'Bronchial Asthma', 'Chicken pox', 'Diabetes ', 'Dengue', '(vertigo) Paroymsal  Positional Vertigo', 'Acne', 'Malaria', 'Drug Reaction', 'Hepatitis B', 'Varicose veins', 'Bronchial Asthma', 'Dengue', 'Drug Reaction', 'Hyperthyroidism', 'Urinary tract infection', 'Hepatitis B', 'hepatitis A', 'Gastroenteritis', 'Heart attack', '(vertigo) Paroymsal  Positional Vertigo', 'Acne', 'Typhoid', 'Tuberculosis', 'Pneumonia', 'Hypoglycemia', 'Malaria', '(vertigo) Paroymsal  Positional Vertigo', 'Typhoid', 'hepatitis A', 'Osteoarthristis', 'Hepatitis D', 'Gastroenteritis', 'Malaria', 'Arthritis', 'Arthritis', 'Hypoglycemia', 'Hypertension ', 'Acne', 'Typhoid', 'Acne', 'Acne', 'Dengue', 'Bronchial Asthma', 'Bronchial Asthma', 'Hypertension ', 'Migraine', 'Heart attack', 'Hepatitis E', 'Migraine', 'Heart attack', 'Impetigo', 'Peptic ulcer diseae', 'Urinary tract infection', 'Common Cold', 'Acne', 'Varicose veins', 'Hypoglycemia', 'Common Cold', 'Gastroenteritis', 'Acne', 'hepatitis A', 'Acne', 'Tuberculosis', 'Acne', 'Tuberculosis', 'Diabetes ', 'AIDS', 'Acne', 'Migraine', 'Peptic ulcer diseae', 'Osteoarthristis', 'Alcoholic hepatitis', 'Chicken pox', 'Osteoarthristis', 'Peptic ulcer diseae', 'Arthritis', 'Hyperthyroidism', 'Drug Reaction', 'hepatitis A', 'Acne', 'Acne', 'Urinary tract infection', 'Heart attack', 'Migraine', 'Acne', 'Alcoholic hepatitis', 'Allergy', 'Hepatitis E', 'Cervical spondylosis', 'Alcoholic hepatitis', 'Hypothyroidism', 'Chicken pox', 'Impetigo', 'Varicose veins', 'Urinary tract infection', '(vertigo) Paroymsal  Positional Vertigo', 'Malaria', 'Osteoarthristis', 'Acne', 'Hepatitis B', 'Hypothyroidism', 'AIDS', 'Gastroenteritis', 'Alcoholic hepatitis', 'Cervical spondylosis', 'AIDS', 'Acne', 'Impetigo', 'Hepatitis B', 'Migraine', 'Hypertension ', 'Acne', 'Varicose veins', 'Hypothyroidism', 'Tuberculosis', '(vertigo) Paroymsal  Positional Vertigo', 'Hepatitis D', 'Acne', 'Hepatitis D', 'Hepatitis B', 'Jaundice', 'Chicken pox', 'Impetigo', 'Hepatitis D', 'Jaundice', 'Tuberculosis', 'Hepatitis E', 'Acne', 'Tuberculosis', 'Typhoid', 'Gastroenteritis', 'Hepatitis E', 'Urinary tract infection', 'Typhoid', 'Osteoarthristis', 'Hepatitis E', 'GERD', 'Cervical spondylosis', 'Hypertension ', 'Peptic ulcer diseae', 'Heart attack', 'Hepatitis D', 'Tuberculosis', '(vertigo) Paroymsal  Positional Vertigo', 'Migraine', 'Diabetes ', 'Chronic cholestasis', 'Impetigo', '(vertigo) Paroymsal  Positional Vertigo', 'Hepatitis C', 'Pneumonia', 'GERD', 'Gastroenteritis', 'Bronchial Asthma', 'Cervical spondylosis', 'Urinary tract infection', 'Migraine', 'Peptic ulcer diseae', 'Pneumonia', 'Hepatitis C', 'Peptic ulcer diseae', 'Cervical spondylosis', 'Gastroenteritis', 'Hepatitis E', 'Hepatitis E', 'Hepatitis E', 'GERD', 'Acne', 'Osteoarthristis', 'Osteoarthristis', 'Chronic cholestasis', 'Diabetes ', 'Acne', 'Cervical spondylosis', 'Osteoarthristis', 'Tuberculosis', 'Hypothyroidism', 'Hypoglycemia', 'Alcoholic hepatitis', 'Hypoglycemia', 'Hepatitis C', 'Cervical spondylosis', 'Chicken pox', 'Acne', 'Heart attack', 'Hyperthyroidism', 'Varicose veins', 'Gastroenteritis', 'Typhoid', 'Osteoarthristis', 'Malaria', 'Gastroenteritis', 'Jaundice', 'Alcoholic hepatitis', 'Hypoglycemia', 'Hypoglycemia', 'Chicken pox', 'Allergy', 'Diabetes ', 'Impetigo', 'AIDS', 'Hepatitis C', 'Hepatitis C', 'Hepatitis E', 'Hepatitis C', 'Acne', 'Drug Reaction', 'Osteoarthristis', 'Alcoholic hepatitis', 'Varicose veins', 'Cervical spondylosis', 'Gastroenteritis', 'Osteoarthristis', 'Dengue', 'Urinary tract infection', 'Acne', '(vertigo) Paroymsal  Positional Vertigo', 'Typhoid', 'Bronchial Asthma', 'Hepatitis C', 'Hepatitis B', 'Hyperthyroidism', 'Alcoholic hepatitis', 'Drug Reaction', 'Cervical spondylosis', 'Pneumonia', 'Gastroenteritis', 'Tuberculosis', 'Hepatitis B', 'GERD', 'Hypothyroidism', 'Varicose veins', 'Hypertension ', 'Chicken pox', 'Chicken pox', 'Osteoarthristis', 'Urinary tract infection', 'Malaria', 'Cervical spondylosis', 'Hypertension ', 'Osteoarthristis', 'GERD', 'Typhoid', 'Alcoholic hepatitis', 'Typhoid', 'Alcoholic hepatitis', 'AIDS', 'Acne', 'Common Cold', 'Peptic ulcer diseae', 'Acne', 'Jaundice', 'Impetigo', 'hepatitis A', 'Acne', 'Cervical spondylosis', 'Osteoarthristis', 'Chronic cholestasis', 'Osteoarthristis', 'Acne', 'Chronic cholestasis', 'Hyperthyroidism', 'Acne', 'Hypothyroidism', 'GERD', 'Migraine', 'Diabetes ', 'Acne', 'Hyperthyroidism', 'Hepatitis B', 'Jaundice', 'GERD', 'Dengue', 'Acne', 'Acne', 'Impetigo', 'Pneumonia', 'GERD', 'Allergy', 'Pneumonia', 'Acne', 'Hepatitis C', 'Hypothyroidism', 'hepatitis A', 'Acne', 'Varicose veins', 'Heart attack', 'Hepatitis D', 'Impetigo', 'Hypertension ', 'Tuberculosis', 'Arthritis', 'Osteoarthristis', 'Alcoholic hepatitis', 'Migraine', 'Acne', 'Malaria', 'Jaundice', 'Jaundice', 'Typhoid', 'Dengue', 'Typhoid', 'Hypoglycemia', 'Hyperthyroidism', 'Hepatitis E', 'Tuberculosis', 'Acne', 'Hepatitis B', 'Common Cold', 'Urinary tract infection', '(vertigo) Paroymsal  Positional Vertigo', 'Acne', 'Hepatitis E', 'hepatitis A', 'Peptic ulcer diseae', 'Cervical spondylosis', 'Acne', 'Arthritis', 'Hypoglycemia', 'Cervical spondylosis', 'Common Cold', '(vertigo) Paroymsal  Positional Vertigo', 'Typhoid', 'GERD', 'Jaundice', 'Common Cold', 'Cervical spondylosis', 'Impetigo', 'Peptic ulcer diseae', 'Cervical spondylosis', 'Hepatitis B', 'Hypothyroidism', 'Hepatitis B', 'Chicken pox', 'Pneumonia', 'Acne', 'Alcoholic hepatitis', 'Malaria', 'Urinary tract infection', 'Osteoarthristis', 'Gastroenteritis', 'Diabetes ', '(vertigo) Paroymsal  Positional Vertigo', 'Hepatitis B', 'Gastroenteritis', 'hepatitis A', 'GERD', 'Hypoglycemia', 'Pneumonia', 'Chronic cholestasis', 'hepatitis A', 'GERD', 'Gastroenteritis', 'Impetigo', 'Heart attack', 'Impetigo', 'Hyperthyroidism', 'Bronchial Asthma', 'Peptic ulcer diseae', 'Hypoglycemia', 'Hepatitis D', 'Osteoarthristis', 'Urinary tract infection', 'Hypothyroidism', 'Hypoglycemia', 'Chronic cholestasis', 'Impetigo', 'Acne', 'Varicose veins', 'Migraine', 'Osteoarthristis', 'Hepatitis D', 'GERD', 'Hyperthyroidism', 'Acne', 'Hepatitis C', '(vertigo) Paroymsal  Positional Vertigo', 'Hyperthyroidism', 'hepatitis A', 'Hepatitis E', 'Acne', 'Jaundice', 'Dengue', 'Diabetes ', 'Allergy', 'Acne', 'Dengue', 'Osteoarthristis', 'Arthritis', 'Cervical spondylosis', 'Alcoholic hepatitis', 'Hypothyroidism', 'Hyperthyroidism', 'AIDS', 'Varicose veins', 'Cervical spondylosis', 'Migraine', 'Cervical spondylosis', 'Alcoholic hepatitis', 'Osteoarthristis', 'Bronchial Asthma', 'Heart attack', 'Hepatitis B', 'hepatitis A', 'Heart attack', 'Hyperthyroidism', 'Typhoid', 'Osteoarthristis', 'Chicken pox', 'Urinary tract infection', 'Common Cold', 'Hypertension ', 'Peptic ulcer diseae', 'Hypothyroidism', 'Impetigo', 'Pneumonia', 'Migraine', 'Osteoarthristis', 'Acne', 'AIDS', 'Jaundice', 'Jaundice', 'Urinary tract infection', '(vertigo) Paroymsal  Positional Vertigo', 'Hypothyroidism', 'Migraine', 'Acne', 'Gastroenteritis', 'Hyperthyroidism', 'Gastroenteritis', 'Drug Reaction', 'Hypoglycemia', 'GERD', 'Allergy', 'Drug Reaction', 'Osteoarthristis', 'Osteoarthristis', 'Typhoid', 'Cervical spondylosis', 'Peptic ulcer diseae', 'Urinary tract infection', 'Hepatitis C', 'Acne', 'Hypothyroidism', 'Tuberculosis', 'Pneumonia', 'Impetigo', 'GERD', 'Hepatitis D', 'Heart attack', '(vertigo) Paroymsal  Positional Vertigo', 'Urinary tract infection', 'Pneumonia', 'Drug Reaction', 'Acne', 'Dengue', 'Tuberculosis', 'Malaria', 'Osteoarthristis', 'Alcoholic hepatitis', 'Hypoglycemia', 'Hepatitis C', 'Heart attack', 'Hypothyroidism', 'Hepatitis D', 'Pneumonia', 'Acne', 'Acne', 'Migraine', 'Hypoglycemia', 'Chicken pox', 'Hypertension ', 'Hepatitis D', 'Arthritis', 'Typhoid', 'Hypothyroidism', 'Migraine', 'Acne', 'Hyperthyroidism', 'AIDS', 'Osteoarthristis', 'AIDS', 'Hepatitis B', 'Varicose veins', '(vertigo) Paroymsal  Positional Vertigo', 'Chicken pox', 'Cervical spondylosis', 'Alcoholic hepatitis', 'Urinary tract infection', 'Tuberculosis', 'Osteoarthristis', 'Diabetes ', 'Hepatitis E', 'Acne', 'Hepatitis D', 'Jaundice', 'Hepatitis B', 'Pneumonia', 'hepatitis A', 'Hypertension ', 'Arthritis', 'Osteoarthristis', 'Osteoarthristis', 'Hepatitis D', 'Acne', 'hepatitis A', 'Allergy', 'Allergy', 'Peptic ulcer diseae', 'Bronchial Asthma', 'Hepatitis E', 'Varicose veins', 'Hepatitis E', 'Acne', 'Dengue', 'Typhoid', 'Cervical spondylosis', 'Osteoarthristis', 'Cervical spondylosis', 'Diabetes ', 'Dengue', 'Acne', 'Acne', 'Allergy', 'Peptic ulcer diseae', 'Acne', 'Peptic ulcer diseae', 'Hyperthyroidism', 'Cervical spondylosis', 'Hypoglycemia', 'Acne', 'Hepatitis B', 'hepatitis A', 'Hepatitis B', 'Hepatitis E', 'Osteoarthristis', 'Acne', 'Migraine', 'Allergy', 'Drug Reaction', 'Hepatitis D', 'Arthritis', 'Arthritis', 'Migraine', 'Heart attack', 'Allergy', 'Allergy', 'Hepatitis E', 'Dengue', 'Malaria', 'Malaria', 'Tuberculosis', 'Chicken pox', 'Common Cold', 'Acne', 'GERD', 'Typhoid', 'Chronic cholestasis', 'Varicose veins', 'Diabetes ', 'Osteoarthristis', 'Cervical spondylosis', '(vertigo) Paroymsal  Positional Vertigo', 'Impetigo', '(vertigo) Paroymsal  Positional Vertigo', 'Diabetes ', 'hepatitis A', 'Varicose veins', 'Chronic cholestasis', 'Varicose veins', 'Alcoholic hepatitis', 'Hyperthyroidism', 'Alcoholic hepatitis', 'Chronic cholestasis', 'Hepatitis D', 'Peptic ulcer diseae', 'Heart attack', 'Hyperthyroidism', 'Gastroenteritis', 'Hypertension ', 'Typhoid', 'Hypoglycemia', 'Acne', 'Typhoid', 'Jaundice', 'Hypothyroidism', 'AIDS', 'Jaundice', 'Peptic ulcer diseae', 'Hypothyroidism', 'Alcoholic hepatitis', 'Hypertension ', 'Impetigo', 'Heart attack', 'Allergy', 'Heart attack', 'Hypothyroidism', 'Acne', 'Arthritis', 'Heart attack', 'Chronic cholestasis', 'Osteoarthristis', 'Tuberculosis', 'Urinary tract infection', 'Varicose veins', 'Gastroenteritis', 'Chicken pox', 'Urinary tract infection', 'Jaundice', 'Gastroenteritis', 'AIDS', 'Acne', 'Dengue', 'Chronic cholestasis', 'Varicose veins', 'Chronic cholestasis', 'Hypothyroidism', 'hepatitis A', 'Cervical spondylosis', 'Hepatitis B', 'Pneumonia', 'Osteoarthristis', 'Alcoholic hepatitis', 'Allergy', 'Dengue', 'Urinary tract infection', 'Common Cold', 'Varicose veins', 'Alcoholic hepatitis', 'Gastroenteritis', 'Chronic cholestasis', 'Hepatitis C', 'Dengue', 'Migraine', 'Jaundice', 'Jaundice', 'Peptic ulcer diseae', '(vertigo) Paroymsal  Positional Vertigo', 'Arthritis', 'Acne', 'hepatitis A', 'Pneumonia', 'Alcoholic hepatitis', 'Pneumonia', 'Gastroenteritis', 'Acne', 'Arthritis', 'Cervical spondylosis', 'Drug Reaction', 'Drug Reaction', 'Chicken pox', 'Migraine', 'Cervical spondylosis', '(vertigo) Paroymsal  Positional Vertigo', 'Arthritis', 'Hyperthyroidism', 'Diabetes ', 'Acne', 'Gastroenteritis', 'Gastroenteritis', 'Pneumonia', 'GERD', 'Acne', 'Varicose veins', 'Varicose veins', 'Gastroenteritis', 'Diabetes ', 'Impetigo', 'Osteoarthristis', 'Urinary tract infection', 'Hepatitis D', 'Acne', 'Jaundice', 'hepatitis A', 'Diabetes ', '(vertigo) Paroymsal  Positional Vertigo', 'Dengue', 'Alcoholic hepatitis', 'Diabetes ', 'Dengue', 'Cervical spondylosis', 'Dengue', 'Impetigo', 'Common Cold', 'Bronchial Asthma', 'Tuberculosis', 'Pneumonia', 'Acne', 'GERD', 'Hepatitis D', 'Arthritis', 'Impetigo', 'Acne', 'Hep

In [59]:
y_true = y_test

In [68]:
from sklearn.metrics import accuracy_score , precision_score , recall_score , f1_score ,confusion_matrix,classification_report

print("Accuracy:", accuracy_score(y_true, y_pred))
# print("Precision:", precision_score(y_true, y_pred , average='binary'))
# print("Recall:", recall_score(y_true, y_pred))
# print("F1-Score:", f1_score(y_true, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))
# print(classification_report(y_true, y_pred, target_names=['Class 0', 'Class 1']))

Accuracy: 0.8733812949640288
Confusion Matrix:
 [[34  0  0 ...  0  0  0]
 [ 0 27  0 ...  0  0  0]
 [ 0  0 34 ...  0  0  0]
 ...
 [ 0  0  4 ... 36  0  0]
 [ 0  0  0 ...  0 34  0]
 [ 0  0  0 ...  0  0 36]]

In [76]:
model.predict([[1,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0]])

C:\Users\singh\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array(['Diabetes '], dtype=object)